apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tdd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-tdd-app
  template:
    metadata:
      labels:
        app: flask-tdd-app
    spec:
      containers:
      - name: flask-tdd
        image: swport/flask-tdd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-tdd-service
spec:
  selector:
    app: flask-tdd-app # should be same with Deployment.spec.template.metadata.labels.app
  ports:
  - port: 8000
    targetPort: 5000
    nodePort: 30007     # Optional: Specify a NodePort (can be in the range 30000-32767)
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-tdd-ingress
  # annotations: 
  # labels:
  #   name: flask-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: flask-tdd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-tdd-service
            port: 
              number: 80
